@startuml
'https://plantuml.com/sequence-diagram

main -> labyJeu: update(seconde, clavier)
activate labyJeu

labyJeu-> perso : getX()
activate perso
perso --> labyJeu : 1
deactivate perso

labyJeu -> perso : getY()
activate perso
perso --> labyJeu : 1
deactivate perso

labyJeu -> laby : getCase(1,1)
activate laby
laby --> labyJeu :CaseDeclancheur cd
deactivate laby

labyJeu -> cd : getType()
activate cd
cd --> labyJeu : 'D'
deactivate cd

labyJeu -> cd : faireEffet(perso)
activate cd
cd -> terminal : Systeme.out.println("Case déclenchée")
activate terminal
terminal --> cd
deactivate terminal
cd --> labyJeu
deactivate cd
labyJeu --> main
deactivate labyJeu

@enduml