@startuml
'https://plantuml.com/sequence-diagram
participant "MainJeu" as mj
create Scanner
mj -> Scanner : new
mj -> Scanner : sc.next()
activate Scanner
Scanner -> Console
activate Console
Console --> Scanner
deactivate Console
Scanner --> mj : String nomlaby
deactivate Scanner
create labyJeu
mj -> labyJeu : new labyJeu(nomlaby)
create LabyDessin
mj-> LabyDessin : new
mj-> MoteurJeu : setFPS(fps)
activate MoteurJeu
    MoteurJeu --> mj
deactivate MoteurJeu
mj-> LabyDessin : LabyDessin.TAILLE_RECTANGLE
activate LabyDessin
LabyDessin --> mj: int taille
deactivate LabyDessin
mj-> MoteurJeu : setTaille(Labyjeu.getLabi().getLength() * taille, Labyjeu.getLabi().getLengthY()* taille)
activate MoteurJeu
MoteurJeu --> mj
deactivate MoteurJeu
mj-> MoteurJeu : launch(Labyjeu,LabyDessin)
activate MoteurJeu
MoteurJeu --> mj
deactivate MoteurJeu

@enduml