@startuml
'https://plantuml.com/sequence-diagram
participant "MainJeu" as m
create Labyjeu
m -> Labyjeu : new
create LabyDessin
m -> LabyDessin : new
m -> MoteurJeu : setFPS(fps)
activate MoteurJeu
    MoteurJeu --> m
deactivate MoteurJeu
m -> LabyDessin : LabyDessin.TAILLE_RECTANGLE
activate LabyDessin
LabyDessin --> m : int taille
deactivate LabyDessin
m -> MoteurJeu : setTaille(Labyjeu.getLabi().getLength() * taille, Labyjeu.getLabi().getLengthY()* taille)
activate MoteurJeu
MoteurJeu --> m
deactivate MoteurJeu
m -> MoteurJeu : launch(Labyjeu,LabyDessin)
activate MoteurJeu

MoteurJeu --> m
deactivate MoteurJeu
@enduml