@startuml
'https://plantuml.com/sequence-diagram

main -> labyJeu: update(seconde, clavier)
activate labyJeu

labyJeu-> perso : getX()
activate perso
perso --> labyJeu : 1
deactivate perso

labyJeu -> perso : getY()
activate perso
perso --> labyJeu : 1
deactivate perso

labyJeu -> laby : getCase(1,1)
activate laby
laby --> labyJeu :CasePieges casepiegee
deactivate laby

labyJeu ->casepiegee : isAmorce()
activate casepiegee
casepiegee --> labyJeu : true
deactivate casepiegee

labyJeu -> casepiegee : faireEffet(perso)
activate casepiegee
casepiegee -> perso : perdrePv(casepiegee.degat)
activate perso
perso --> casepiegee
deactivate perso
casepiegee --> labyJeu
deactivate casepiegee

labyJeu -> casepiegee : changerAmorce
activate casepiegee
casepiegee --> labyJeu :
deactivate casepiegee

labyJeu --> main
deactivate labyJeu

@enduml